"""simulator.ui.inspector.inspector_panel

A parameter inspector for the selected block.

What this version fixes/implements (MVP -> usable):
- Specialized editors for the blocks you actually need to do control work:
    * TF: numerator/denominator editor
    * Gain: scalar gain editor
    * Sum: n_inputs + per-input sign (+/-) editor
    * Step: amplitude + t0
    * Scope: label
  Everything else falls back to a generic key/value editor.

- Validation on Apply using the BlockRegistry spec's validate_params().
  Errors are shown inline and Apply is blocked until fixed.

Contract:
- Emits sig_block_updated(block_id, params_dict)
  (keeps existing MainWindow wiring unchanged).

Notes:
- Sum signs are stored in params["signs"] and params["n_inputs"]. The IR ports' sign
  values are regenerated by registry spec default_block() during graph_to_ir().

Updated:
- Treats ("tf", "tf_flipped") the same, so TF (Flipped) reuses the Num/Den editor.
- Treats ("sum", "sum_glyph") the same, so the Sum Glyph reuses the same n_inputs/sign editor.
- UI polish only: adds header, section group boxes, spacing, and a compact error banner.
  (No behavior changes to data collection/validation.)
"""

from __future__ import annotations

from typing import Any

from PySide6 import QtCore, QtWidgets

from simulator.simulator.blocks.registry import BlockRegistry
from simulator.simulator.core.ir.types import Block

# Optional specialized editors (we created these in simulator/ui/inspector/editors.py).
# We keep local fallbacks so the app stays runnable even if that module changes.
try:  # pragma: no cover
    from .editors import NumDenEditor, VectorEditor  # type: ignore
except Exception:  # pragma: no cover

    class VectorEditor(QtWidgets.QLineEdit):
        """Fallback vector editor: comma-separated floats."""

        def __init__(self, values: list[float] | None = None, parent: QtWidgets.QWidget | None = None) -> None:
            super().__init__(parent)
            self.setText(",".join(str(x) for x in (values or [])))

        def value(self) -> list[float]:
            t = self.text().strip()
            if not t:
                return []
            out: list[float] = []
            for part in t.replace(";", ",").split(","):
                p = part.strip()
                if not p:
                    continue
                out.append(float(p))
            return out

    class NumDenEditor(QtWidgets.QWidget):
        """Fallback TF editor: two vector lines."""

        def __init__(
            self,
            num: list[float] | None = None,
            den: list[float] | None = None,
            parent: QtWidgets.QWidget | None = None,
        ) -> None:
            super().__init__(parent)
            self._num = VectorEditor(num or [1.0], self)
            self._den = VectorEditor(den or [1.0, 1.0], self)
            form = QtWidgets.QFormLayout(self)
            form.setContentsMargins(0, 0, 0, 0)
            form.addRow("num", self._num)
            form.addRow("den", self._den)

        def value(self) -> dict[str, list[float]]:
            return {"num": self._num.value(), "den": self._den.value()}


class InspectorPanel(QtWidgets.QWidget):
    sig_block_updated = QtCore.Signal(str, dict)  # block_id, params

    def __init__(self, *, registry: BlockRegistry, parent: QtWidgets.QWidget | None = None) -> None:
        super().__init__(parent)
        self.setObjectName("InspectorPanel")

        self._registry = registry
        self._block: Block | None = None

        # Header
        self._header = QtWidgets.QFrame()
        self._header.setObjectName("InspectorHeader")
        self._header.setFrameShape(QtWidgets.QFrame.NoFrame)

        self._title = QtWidgets.QLabel("Inspector")
        self._title.setObjectName("InspectorTitle")
        self._title.setWordWrap(True)

        self._subtitle = QtWidgets.QLabel("No selection")
        self._subtitle.setObjectName("InspectorSubtitle")
        self._subtitle.setWordWrap(True)

        hlay = QtWidgets.QVBoxLayout(self._header)
        hlay.setContentsMargins(10, 10, 10, 8)
        hlay.setSpacing(2)
        hlay.addWidget(self._title)
        hlay.addWidget(self._subtitle)

        # Inline validation / status (banner)
        self._status_frame = QtWidgets.QFrame()
        self._status_frame.setObjectName("InspectorStatusFrame")
        self._status_frame.setFrameShape(QtWidgets.QFrame.NoFrame)

        self._status = QtWidgets.QLabel("")
        self._status.setObjectName("InspectorStatus")
        self._status.setWordWrap(True)

        s_lay = QtWidgets.QHBoxLayout(self._status_frame)
        s_lay.setContentsMargins(10, 8, 10, 8)
        s_lay.addWidget(self._status)
        self._status_frame.hide()

        # Outer form (we add section group boxes as spanning rows)
        self._form = QtWidgets.QFormLayout()
        self._form.setContentsMargins(10, 10, 10, 10)
        self._form.setSpacing(8)
        self._form.setLabelAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignVCenter)
        self._form.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)

        self._scroll = QtWidgets.QScrollArea()
        self._scroll.setWidgetResizable(True)
        self._scroll.setFrameShape(QtWidgets.QFrame.NoFrame)

        self._form_container = QtWidgets.QWidget()
        self._form_container.setObjectName("InspectorFormContainer")
        self._form_container.setLayout(self._form)
        self._scroll.setWidget(self._form_container)

        # Apply button row
        self._btn_apply = QtWidgets.QPushButton("Apply")
        self._btn_apply.setObjectName("InspectorApply")
        self._btn_apply.clicked.connect(self._on_apply)
        self._btn_apply.setEnabled(False)

        btn_row = QtWidgets.QHBoxLayout()
        btn_row.setContentsMargins(10, 8, 10, 10)
        btn_row.addStretch(1)
        btn_row.addWidget(self._btn_apply)

        layout = QtWidgets.QVBoxLayout(self)
        layout.setContentsMargins(0, 0, 0, 0)
        layout.setSpacing(0)
        layout.addWidget(self._header)
        layout.addWidget(self._status_frame)
        layout.addWidget(self._scroll, stretch=1)
        layout.addLayout(btn_row)

        # internal editor registry
        self._editors: dict[str, QtWidgets.QWidget] = {}

        # Sum-specific
        self._sum_n_inputs: QtWidgets.QSpinBox | None = None
        self._sum_sign_boxes: list[QtWidgets.QComboBox] = []

        self._apply_styles()

    # -----------------
    # Styling
    # -----------------
    def _apply_styles(self) -> None:
        # Keep styles modest and readable under your light canvas theme.
        # (No dependency on a global theme engine.)
        self.setStyleSheet(
            """
            QFrame#InspectorHeader {
                border-bottom: 1px solid rgba(0,0,0,0.08);
                background: rgba(255,255,255,0.0);
            }
            QLabel#InspectorTitle {
                font-size: 14px;
                font-weight: 700;
            }
            QLabel#InspectorSubtitle {
                font-size: 11px;
                color: rgba(0,0,0,0.55);
            }
            QFrame#InspectorStatusFrame {
                margin: 8px 10px 0px 10px;
                border-radius: 8px;
                border: 1px solid rgba(176, 0, 32, 0.25);
                background: rgba(176, 0, 32, 0.08);
            }
            QLabel#InspectorStatus {
                color: rgb(176, 0, 32);
                font-size: 11px;
            }
            QGroupBox {
                margin-top: 8px;
                border: 1px solid rgba(0,0,0,0.10);
                border-radius: 10px;
            }
            QGroupBox::title {
                subcontrol-origin: margin;
                left: 10px;
                padding: 0 6px;
                color: rgba(0,0,0,0.70);
                font-weight: 700;
            }
            QLineEdit, QSpinBox, QDoubleSpinBox, QComboBox {
                padding: 5px 6px;
                border-radius: 8px;
                border: 1px solid rgba(0,0,0,0.18);
                background: rgba(255,255,255,0.85);
            }
            QLineEdit:focus, QSpinBox:focus, QDoubleSpinBox:focus, QComboBox:focus {
                border: 1px solid rgba(45,125,255,0.85);
            }
            QPushButton#InspectorApply {
                padding: 8px 14px;
                border-radius: 10px;
                background: rgb(45, 125, 255);
                color: white;
                font-weight: 700;
            }
            QPushButton#InspectorApply:disabled {
                background: rgba(0,0,0,0.25);
                color: rgba(255,255,255,0.85);
            }
            """
        )

    def _set_status(self, text: str) -> None:
        text = (text or "").strip()
        self._status.setText(text)
        self._status_frame.setVisible(bool(text))

    # -----------------
    # Public API
    # -----------------
    def clear(self) -> None:
        self._block = None
        self._title.setText("Inspector")
        self._subtitle.setText("No selection")
        self._set_status("")
        self._btn_apply.setEnabled(False)
        self._clear_form()

    def set_block(self, block: Block) -> None:
        self._block = block
        self._btn_apply.setEnabled(True)
        self._set_status("")
        self._title.setText(str(block.id))
        self._subtitle.setText(f"Type: {block.type}")

        params = dict(block.params or {})

        # Seed missing defaults from spec (so TF/Gain/Sum show usable fields even on fresh nodes)
        if self._registry.has(block.type):
            try:
                b0 = self._registry.get(block.type).default_block(block_id=block.id)
                for k, v in (b0.params or {}).items():
                    params.setdefault(k, v)
            except Exception:
                pass

        self._render_block(block, params)

    # -----------------
    # Internals
    # -----------------
    def _clear_form(self) -> None:
        while self._form.rowCount():
            self._form.removeRow(0)
        self._editors.clear()
        self._sum_n_inputs = None
        self._sum_sign_boxes = []

    def _section(self, title: str) -> tuple[QtWidgets.QGroupBox, QtWidgets.QFormLayout]:
        gb = QtWidgets.QGroupBox(title)
        gb.setObjectName("InspectorSection")
        fl = QtWidgets.QFormLayout(gb)
        fl.setContentsMargins(12, 14, 12, 12)
        fl.setSpacing(8)
        fl.setLabelAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignVCenter)
        fl.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        return gb, fl

    def _add_section(self, title: str) -> tuple[QtWidgets.QFormLayout, QtWidgets.QGroupBox]:
        gb, fl = self._section(title)
        self._form.addRow(gb)  # spanning row
        return fl, gb

    def _render_block(self, block: Block, params: dict[str, Any]) -> None:
        self._clear_form()

        # Specialized layouts for core blocks
        if block.type in ("tf", "tf_flipped"):
            self._render_tf(params)
            return
        if block.type in ("gain", "gain_flipped"):
            self._render_gain(params)
            return
        if block.type in ("sum", "sum_glyph"):
            self._render_sum(params)
            return
        if block.type == "step":
            self._render_step(params)
            return
        if block.type == "scope":
            self._render_scope(params)
            return

        # Generic fallback
        if not params:
            fl, _ = self._add_section("Parameters")
            fl.addRow(QtWidgets.QLabel("No parameters"), QtWidgets.QLabel(""))
            return

        fl, _ = self._add_section("Parameters")
        for k in sorted(params.keys()):
            fl.addRow(QtWidgets.QLabel(k), self._make_generic_editor(k, params[k]))

    # ------- specialized -------
    def _render_tf(self, params: dict[str, Any]) -> None:
        num = params.get("num", [1.0])
        den = params.get("den", [1.0, 1.0])
        ed = NumDenEditor(num=num, den=den)
        self._editors["__tf__"] = ed

        fl, _ = self._add_section("Transfer Function")
        fl.addRow("num / den", ed)

    def _render_gain(self, params: dict[str, Any]) -> None:
        k = params.get("k", 1.0)
        spin = QtWidgets.QDoubleSpinBox()
        spin.setDecimals(6)
        spin.setRange(-1e12, 1e12)
        try:
            spin.setValue(float(k))
        except Exception:
            spin.setValue(1.0)

        self._editors["k"] = spin
        fl, _ = self._add_section("Gain")
        fl.addRow("k", spin)

    def _render_sum(self, params: dict[str, Any]) -> None:
        fl, _ = self._add_section("Sum (+/−)")

        # n_inputs
        n_inputs = params.get("n_inputs", 2)
        spin = QtWidgets.QSpinBox()
        spin.setRange(2, 8)
        try:
            spin.setValue(int(n_inputs))
        except Exception:
            spin.setValue(2)

        self._sum_n_inputs = spin
        fl.addRow("n_inputs", spin)

        # signs list
        signs = params.get("signs", [1, -1])
        try:
            signs_list = [int(s) for s in signs]
        except Exception:
            signs_list = [1, -1]

        # Normalize length
        while len(signs_list) < spin.value():
            signs_list.append(-1)
        signs_list = signs_list[: spin.value()]

        self._sum_sign_boxes = []
        for i in range(spin.value()):
            cb = QtWidgets.QComboBox()
            cb.addItem("+", userData=1)
            cb.addItem("-", userData=-1)
            cb.setCurrentIndex(0 if signs_list[i] >= 0 else 1)
            self._sum_sign_boxes.append(cb)
            fl.addRow(f"sign[{i}]", cb)

        # If user changes n_inputs, re-render the sign rows in-place.
        def _on_n_inputs_changed(_: int) -> None:
            if not self._block:
                return
            current = self._collect_params_for_sum()
            self._render_sum(current)

        spin.valueChanged.connect(_on_n_inputs_changed)

    def _render_step(self, params: dict[str, Any]) -> None:
        amp = params.get("amplitude", 1.0)
        t0 = params.get("t0", 0.0)

        s_amp = QtWidgets.QDoubleSpinBox()
        s_amp.setDecimals(6)
        s_amp.setRange(-1e12, 1e12)
        try:
            s_amp.setValue(float(amp))
        except Exception:
            s_amp.setValue(1.0)

        s_t0 = QtWidgets.QDoubleSpinBox()
        s_t0.setDecimals(6)
        s_t0.setRange(0.0, 1e12)
        try:
            s_t0.setValue(float(t0))
        except Exception:
            s_t0.setValue(0.0)

        self._editors["amplitude"] = s_amp
        self._editors["t0"] = s_t0

        fl, _ = self._add_section("Step Source")
        fl.addRow("amplitude", s_amp)
        fl.addRow("t0", s_t0)

    def _render_scope(self, params: dict[str, Any]) -> None:
        label = params.get("label", "")
        le = QtWidgets.QLineEdit()
        le.setText(str(label) if label is not None else "")

        self._editors["label"] = le
        fl, _ = self._add_section("Scope")
        fl.addRow("label", le)

    # ------- generic editor helpers -------
    def _make_generic_editor(self, key: str, value: Any) -> QtWidgets.QWidget:
        if isinstance(value, bool):
            cb = QtWidgets.QCheckBox()
            cb.setChecked(bool(value))
            self._editors[key] = cb
            return cb

        if isinstance(value, int) and not isinstance(value, bool):
            sb = QtWidgets.QSpinBox()
            sb.setRange(-2**31, 2**31 - 1)
            sb.setValue(int(value))
            self._editors[key] = sb
            return sb

        if isinstance(value, float):
            sb = QtWidgets.QDoubleSpinBox()
            sb.setDecimals(6)
            sb.setRange(-1e12, 1e12)
            sb.setValue(float(value))
            self._editors[key] = sb
            return sb

        if isinstance(value, (list, tuple)):
            # numeric vectors are common in control; if it fails, fall back to JSON.
            try:
                vec = [float(x) for x in value]
                ve = VectorEditor(vec)
                self._editors[key] = ve
                return ve
            except Exception:
                pass

        # dict/list/other: JSON-ish text
        le = QtWidgets.QLineEdit()
        le.setText(self._to_text(value))
        self._editors[key] = le
        return le

    def _to_text(self, v: Any) -> str:
        if isinstance(v, (list, dict)):
            import json

            return json.dumps(v)
        if v is None:
            return ""
        return str(v)

    def _parse_text(self, text: str) -> Any:
        t = text.strip()
        if t == "":
            return None

        import json

        try:
            return json.loads(t)
        except Exception:
            pass

        # numeric fallback
        try:
            if "." in t or "e" in t.lower():
                return float(t)
            return int(t)
        except Exception:
            return t

    # ------- collect/apply -------
    def _collect_params_for_sum(self) -> dict[str, Any]:
        """Collect current sum editor state (even while rebuilding)."""
        n = self._sum_n_inputs.value() if self._sum_n_inputs is not None else 2
        signs: list[int] = []
        for cb in self._sum_sign_boxes:
            s = cb.currentData()
            signs.append(int(s) if s in (-1, 1) else 1)
        while len(signs) < n:
            signs.append(-1)
        signs = signs[:n]
        return {"n_inputs": int(n), "signs": signs}

    def _collect_params(self) -> dict[str, Any]:
        if not self._block:
            return {}

        # Start from current block params so we don't drop unknown fields.
        params: dict[str, Any] = dict(self._block.params or {})

        if self._block.type in ("tf", "tf_flipped"):
            ed = self._editors.get("__tf__")
            # Preferred: editor provides .value() -> {"num": [...], "den": [...]}
            if hasattr(ed, "value") and callable(getattr(ed, "value")):
                try:
                    v = ed.value()  # type: ignore
                    if isinstance(v, dict):
                        params.update(v)
                        return params
                except Exception:
                    pass
            # Fallback: editor exposes .num()/.den()
            if hasattr(ed, "num") and hasattr(ed, "den"):
                try:
                    params["num"] = list(ed.num())  # type: ignore
                    params["den"] = list(ed.den())  # type: ignore
                except Exception:
                    pass
            return params

        if self._block.type in ("sum", "sum_glyph"):
            params.update(self._collect_params_for_sum())
            return params

        # Generic collection for known widget types.
        for k, w in self._editors.items():
            if k == "__tf__":
                continue

            if isinstance(w, QtWidgets.QLineEdit):
                # If this is a VectorEditor-like widget, prefer its parsed values.
                if hasattr(w, "values") and callable(getattr(w, "values")):
                    try:
                        params[k] = w.values()  # type: ignore
                        continue
                    except Exception:
                        pass
                if hasattr(w, "value") and callable(getattr(w, "value")):
                    try:
                        params[k] = w.value()  # type: ignore
                        continue
                    except Exception:
                        pass

                params[k] = self._parse_text(w.text())

            elif isinstance(w, QtWidgets.QCheckBox):
                params[k] = bool(w.isChecked())

            elif isinstance(w, QtWidgets.QSpinBox):
                params[k] = int(w.value())

            elif isinstance(w, QtWidgets.QDoubleSpinBox):
                params[k] = float(w.value())

            elif hasattr(w, "value"):
                try:
                    params[k] = w.value()  # type: ignore
                except Exception:
                    pass

        return params

    def _validate(self, params: dict[str, Any]) -> list[str]:
        if not self._block:
            return []
        if not self._registry.has(self._block.type):
            return []
        try:
            spec = self._registry.get(self._block.type)
            return list(spec.validate_params(params))
        except Exception as e:
            return [str(e)]

    def _on_apply(self) -> None:
        if not self._block:
            return

        params = self._collect_params()
        errs = self._validate(params)
        if errs:
            self._set_status("\n".join(errs))
            return

        self._set_status("")
        self.sig_block_updated.emit(self._block.id, params)
